spring:
  application:
    name: Team
  data:
    mongodb:
      password: painfulkafka
      username: kafkadmin
      host: 158.101.206.85
      port: 27017
      authentication-database: admin
  datasource:
    hikari:
      auto-commit: true
  devtools:
    livereload:
      enabled: true
    add-properties: true
  profiles:
    active: dev
  kafka:
    bootstrap-servers: 158.101.206.85:9092
    consumer:
      group-id: group-consumer
      enable-auto-commit: false
      auto-offset-reset: earliest
server:
  port: 8080
  http2:
    enabled: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
logging:
  level:
    root: info
    org.springframework.web: warn
    org.springframework.security: debug
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
message-topic: main
