spring:
  application:
    name: Team
  data:
    mongodb:
      username: root
      password: root
      host: mongo
      database: test
      port: 27017
      authentication-database: admin
  datasource:
    hikari:
      auto-commit: true
  kafka:
    bootstrap-servers: ${bootstrap-servers:127.0.0.1}:9092
    consumer:
      group-id: group-consumer
      enable-auto-commit: false
      auto-offset-reset: earliest
server:
  port: ${port:8080}
  address: 127.0.0.1
  http2:
    enabled: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
logging:
  level:
    root: info
    org.springframework.web: debug
  file:
    name: resources/logs/application-debug.log
    clean-history-on-start: false

message-topic: main
