spring:
  application:
    name: Team
  datasource:
    url: mongodb://158.101.206.85:27017/test
    username: kafkadmin
    password: painfulkafka
    hikari:
      auto-commit: true
  devtools:
    livereload:
      enabled: true
    add-properties: true
  profiles:
    active: dev
  kafka:
    bootstrap-servers: 158.101.206.85:9092
    consumer:
      group-id: group-consumer # ??? what is this
      enable-auto-commit: true # todo google it
      auto-offset-reset: latest
server:
  port: ${port:8080}
  address: 127.0.0.1
  http2:
    enabled: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
logging:
  level:
    root: info
    org.springframework.web: off
  file:
    name: logs/application-debug.log
message-topic: Chat-Topic
