spring:
  application:
    name: Team
  data:
    mongodb:
      username: ${username:root}
      password: ${password:root}
      host: ${host:mongo}
      database: application
      port: ${port:27017}
      authentication-database: admin
  datasource:
    hikari:
      auto-commit: true
  kafka:
    bootstrap-servers: ${bootstrap-servers:kafka}:9092
    consumer:
      group-id: group-consumer
      enable-auto-commit: false
      auto-offset-reset: earliest
server:
  port: ${port:8080}
  http2:
    enabled: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
logging:
  level:
    root: info
  file:
    name: logs/application-debug.log
    clean-history-on-start: false

message-topic: main
