spring:
  application:
    name: Team
  data:
    mongodb:
      password: painfulkafka
      username: kafkadmin
      host: 158.101.206.85
      port: 27017
      authentication-database: admin
  datasource:
    hikari:
      auto-commit: true
  devtools:
    livereload:
      enabled: true
    add-properties: true
  profiles:
    active: dev
  kafka:
    bootstrap-servers: 158.101.206.85:9092
    consumer:
      group-id: group-consumer # ??? what is this
      enable-auto-commit: false # todo google it
      auto-offset-reset: earliest
server:
  port: ${port:8080}
  address: 127.0.0.1
  http2:
    enabled: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
logging:
  level:
    root: info
    org.springframework.web: warn
    org.springframework.security: debug
  file:
    name: logs/application-debug.log
    clean-history-on-start: true

message-topic: main
