spring:
  application:
    name: Team
  data:
    mongodb:
      username: ${username:root}
      password: ${password:root}
      host: ${host:mongo}
      database: ${database:application}
      port: ${port:27017}
      authentication-database: admin
  datasource:
    hikari:
      auto-commit: true
  kafka:
    bootstrap-servers: ${bootstrap-servers:127.0.0.1}:9092
    consumer:
      group-id: group-consumer
      enable-auto-commit: false
      auto-offset-reset: earliest
server:
  port: ${port:8080}
  http2:
    enabled: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
logging:
  level:
    root: info
  file:
    name: logs/application.log
    clean-history-on-start: false
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

message-topic: main
