version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: my_zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: my_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "main:1:3"


  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=my_mongo
      - MONGO_INITDB_ROOT_USERNAME=kafkadmin
      - MONGO_INITDB_ROOT_PASSWORD=painfulkafka
    ports:
      - "27017:27017"
    restart: unless-stopped

  app:
    image: dimitryvargin/spring-chat
    container_name: spring-chat
    ports:
    - "8080:8080"