global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'Apache Kafka Monitoring'
#    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'jmxexporter:5556'
        labels:
          env: 'prod'

  - job_name: 'Spring Boot Application Monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'app:8080'
        labels:
          env: 'prod'