name: Build with Gradle

on:
  push:
    branches: [ devops_auto_ci_cd ]

jobs:            
  DeplloyToDockerHub:
    runs-on: ubuntu-latest
    steps:
        - name: Getting sources
          uses: actions/checkout@v2
          
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build
          run: |
            docker build -t dimitryvargin/spring-chat .
            
        - name: Push
          run: |
            docker push dimitryvargin/spring-chat
