name: Build with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting sources
        uses: actions/checkout@v2
      - name: Setting up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Granting permission
        run: chmod +x gradlew
      - name: Building by Gradle
        run: ./gradlew build
      - name: Moving *.jar
        run: cp build/libs/*.jar Team.jar
      - name: Uploading jar artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.jar