name: Build with Gradle

on:
  push:
    branches: [ devops_auto_ci_cd ]

jobs:            
  DeplloyToDockerHub:
    runs-on: ubuntu-latest
    steps:
        - name: Getting sources
          uses: actions/checkout@v2
          
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PAS }}
        
        - name: Build
          run: |
            docker build -t dimitryvargin/spring-chat .
            
        - name: Push
          run: |
            docker push dimitryvargin/spring-chat
            
  RunOnServer:
    runs-on: ubuntu-latest
    needs: [DeplloyToDockerHub,]
    
    steps:
    - name: run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: demo
        password: ${{ secrets.DOCKER_PAS }}
        port: 22
        script: |
          touch HELLOWORLD.txt
