name: ci/cd

on:
  push:
    branches: [ master, workflow ]

jobs:
 # Build:
    #runs-on: ubuntu-latest
   # steps:
     # - name: Getting sources
     #   uses: actions/checkout@v2
     # - name: Setting up JDK
     #   uses: actions/setup-java@v1
     #   with:
     #     java-version: 11
     # - name: Building by Gradle
     #   run: chmod +x gradlew && ./gradlew build && mv build/libs/*.jar Team.jar
     # - name: Realising Jar
      #  uses: "marvinpinto/action-automatic-releases@latest"
      #  with:
      #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #    automatic_release_tag: "latest"
      #    prerelease: true
       #   title: "Development Build"
       #   files: |
        #    *.jar
  dockerLogin:
    runs-on: ubuntu-latest
    steps:
  #    - name: Set up QEMU
  #      uses: docker/setup-qemu-action@v1

  #    - name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v1
#
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

   #   - name: Build and push
    #    id: docker_build
    #    uses: docker/build-push-action@v2
    #    with:
    #      push: true
    #      tags: ${{ secrets.DOCKER_USER }}/java-docker:latest

   #   - name: Image digest
   #     run: echo ${{ steps.docker_build.outputs.digest }}
  docker-compose:
    runs-on: ubuntu-latest
    needs: dockerLogin
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: cd ./docker ; ls ; docker-compose up -d ; docker push ${{ secrets.DOCKER_USER }}/java_dockercompose
        
